### ISSUE TITLE
Getting Plinder-PL50 subdataset

### ISSUE THREAD

**Issue by VectorShi** [plinder-org/plinder#21]
Great work! 

Is there any available way to fetch Plinder-PL50, which is utlized to test diffdock in your paper, without runing your pipeline?

I will be very grateful.

Best, 
Liang

**Comment by VectorShi** [comment]
For example, can you provide a parquet file similar to "splits_metaflow_config_split_v2_split_multi_graph_yaml.parquet"

**Comment by patrickbryant1** [comment]
Yes, for all main splits please. It is quite difficult to use this data at the moment.

**Comment by OleinikovasV** [comment]
@VectorShi  - please, see the reply here:
https://github.com/plinder-org/plinder/issues/20#issuecomment-2283932341

We will keep updating on the improvements for data loading and further splits in the ISSUE https://github.com/plinder-org/plinder/issues/20 , hence will close this for now.

**Comment by VectorShi** [comment]
Thank you!
It's really a great help.
