### ISSUE TITLE
V2 Split for Plinder

### ISSUE THREAD

**Issue by danielzeng-gt** [plinder-org/plinder#27]
Dear Plinder Team,

Thank you for your excellent work in curating the dataset and extensive work creating the splits. It certainly makes for a solid benchmark with improved deleaking between the training and test sets compared to existing splits.

I wanted to inquire about the release of the V2 version of the splits/data. The README mentioned the release by August 18th, but the GCS bucket does not appear to have been updated yet.

I was wondering if there's an update on when we can expect the V2 release?

**Comment by yusuf1759** [comment]
@danielzeng-gt , thank you so much for the interest! 
The new dataset is available for download here: `gs://plinder/2024-06/v2/`
And the splits can be accessed at `splits/split.parquet`.

We will be working in the next couple of days to update the website, repo and other documentation accordingly to the new split.
