### ISSUE TITLE
about the local plinder dir 

### ISSUE THREAD

**Issue by Getiann** [plinder-org/plinder#67]
I want to try python API. I followed the steps in the python API tutorial. 
![screenshot-20240927-155348](https://github.com/user-attachments/assets/a13ec50f-0d0d-4019-b56b-b07564e3c20f)
In this step, an error has occurred.

ValueError: '/home_data/home/my/path/.local/share/plinder/2024-06/v2/entries/ag.zip' is not in the subpath of '/home_data/home/my/path/.local/share/plinder/2024-06/tutorial' OR one path is relative and the other is absolute. 

How should I to fix it!
Thanks

**Comment by OleinikovasV** [comment]
Hi, @Getiann,
Seems like you may have an issue with mixed specifications of your config - you should be working with a `tutorial` subset, but it seems like you are pointing to a `v2` iteration directory.
Is it possible that you have changed some of these configs from those that were originally specified in the documentation?
Try reseting your notebook back to original version.

If that does not work, could you please provide the output for these commands:

```
import plinder.core.utils.config
cfg = plinder.core.get_config()

print(f"local cache directory: {cfg.data.plinder_dir}")
print(f"remote data directory: {cfg.data.plinder_remote}")
print(f"release: {cfg.data.plinder_release}")
print(f"iteration: {cfg.data.plinder_iteration}")

print(f"version: {plinder.__version__}")
```

**Comment by Getiann** [comment]
Thank you, @OleinikovasV 
The problem is solved！
My remote data directory is wrong.
![image](https://github.com/user-attachments/assets/7f467419-ab93-4af3-a8c4-08ad099cc88f)
It's my carelessness.
