### ISSUE TITLE
about 'cluster'

### ISSUE THREAD

**Issue by Getiann** [plinder-org/plinder#68]
why the 'directed' is False?
![image](https://github.com/user-attachments/assets/41335441-c833-46a0-b9e5-cf6f64cf26b6)

**Comment by Getiann** [comment]
The PLINDER is an excellent database. I will be utilizing PLINDER to train a model, and I anticipate having numerous questions throughout the process. Thank you for your understanding.

**Comment by OleinikovasV** [comment]
@Getiann - thank you for you questions! For the detailed discussions about the dataset - please join [PLINDER user group discord server](https://discord.com/invite/KgUdMn7TuS) - we would be happy to address the further questions there!

**Comment by Getiann** [comment]
Oh！Thank you! @OleinikovasV
